### ISSUE TITLE
能打包为exe吗？

### ISSUE THREAD

**Issue by badboycxcc** [XiaoliChan/wmiexec-Pro#1]

**Comment by XiaoliChan** [comment]
感谢您使用本项目，但是目前没有想着打包成exe，以为vbscripts目录下的脚本不会跟着一起打包进去（这个得想想办法），如果你是护网现场工作的话，你只需要安装python3 + impacket即可使用该项目

**Comment by badboycxcc** [comment]
不是护网，只是目标机器上没有Python环境。

**Comment by XiaoliChan** [comment]
> 不是护网，只是目标机器上没有Python环境。

打包成exe的话，vbscripts也需要一起落地

**Comment by XiaoliChan** [comment]
Update in 2024:

可以使用这个项目实现 `https://github.com/oiweiwei/go-msrpc`
