### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ffsfwnuiaww** [XiaoliChan/wmiexec-Pro#7]
D:\tools\wmiexec-Pro-0.2.7>python wmiexec-pro.py  administrator:@10.11.18.18 exec-command -shell
Impacket v0.11.0 - Copyright 2023 Fortra

Password:
[-] ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver_major | B=5 | b''[:1]'")

**Comment by ffsfwnuiaww** [comment]
D:\tools\wmiexec-Pro-0.2.7>python wmiexec-pro.py  administrator@10.10.211.7 -hashes aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0 rdp -enable
Impacket v0.11.0 - Copyright 2023 Fortra

[-] ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver_major | B=5 | b''[:1]'")

**Comment by XiaoliChan** [comment]
This error is caused by impacket, some issues in impacket is non-fixed.

You can open an issue ticket at https://github.com/fortra/impacket

**Comment by ffsfwnuiaww** [comment]
<img width="915" alt="image" src="https://github.com/XiaoliChan/wmiexec-Pro/assets/89639412/6bea7016-91e7-4dc8-af57-76a6d64319df">


我看提交了一个，你提交的这个报错跟我发的这个一样么

**Comment by XiaoliChan** [comment]
> 我看提交了一个，你提交的这个报错跟我发的这个一样么

Haha, 这个是修复Kerberos认证的，和这个无关的

**Comment by XiaoliChan** [comment]
Hi @ffsfwnuiaww, did U use proxy in this issue?
