### ISSUE TITLE
域账号 rpc_s_access_denied

### ISSUE THREAD

**Issue by bcdlbgm** [XiaoliChan/wmiexec-Pro#8]
对于域内账号好像有问题？
![image](https://github.com/XiaoliChan/wmiexec-Pro/assets/45490024/10fe6324-75bc-45fe-83cf-f71d074674a3)
不清楚为什么，抓包发现我的10域内主机与79域控验证身份信息会失败，但我密码和hash是没问题的。
![image](https://github.com/XiaoliChan/wmiexec-Pro/assets/45490024/bc273f2c-5fae-46df-8925-8d51f13df5cd)

正常主机账号密码是没问题的，只存在与域内交互时出现问题。我很疑惑，不清楚是我环境问题还是工具问题。

**Comment by XiaoliChan** [comment]
域认证使用slash(“/”)，而不是backslash("\")

密码有特殊字符，需要双引号括起来
